### ISSUE TITLE
Add a README and composer.json description

### ISSUE THREAD

**Issue by philsturgeon** [kaystrobach/FLOW.Pdf#1]
Without a description, its hard for people to work out which package to use other than clicking all the way through to your GitHub.

**Comment by rizerzero** [comment]
Right , still no helpful example file .

**Comment by kaystrobach** [comment]
IMHO there is an example in the README ... what's missing in your opinion?

**Comment by philsturgeon** [comment]
Unfortunately the example looks like one big chunk of XML + HTML with no real explanation of how things fit together, or how anything is run.

It should be a hello world style "do this to get going" so anyone can look at it and understand the workflow within seconds.

Otherwise people will just click back and use the next one, even though your solution might be exactly what they need!

**Comment by kaystrobach** [comment]
just added another ultra short example. i think, as this is developer oriented and very common in TYPO3.Flow this should be sufficient, if you still miss something feel free to open a pull request.

**Comment by philsturgeon** [comment]
Better. I think explicitly stating this is a package for TYPO3.Flow would help people realize its _not_ for them more quickly. :)

**Comment by kaystrobach** [comment]
ok, the name clarifies that IMHO, but will add that as well now

**Comment by philsturgeon** [comment]
The name clarifies it only if you know what FLOW is. If you don’t, you’ll be confused - like I was.

Thanks for listening and for doing things. You’re a star.

**Comment by kaystrobach** [comment]
thank you for the flowers :smile:

**Comment by kaystrobach** [comment]
@philsturgeon maybe you should stick to mpdf directly which i used in the example to have a nice pdf library, which is independet from FLOW :dancer:

**Comment by philsturgeon** [comment]
Oh I’m not using this. My point is that when people search for “PDF” and this pops up, there is nothing to tell the user that its not an option for them unless they’re using whatever foo system.

You resolved my concerns perfectly, so we’re good here.
